FROM python:3.11.3

WORKDIR /app
COPY requirements.txt ./
RUN ["python", "-m", "pip", "install", "--upgrade", "pip"]
RUN ["pip", "install", "-r", "requirements.txt"]

EXPOSE 80

COPY . .
RUN ["python", "manage.py", "migrate"]

CMD ["python", "manage.py", "runserver", "0.0.0.0:80"]
