FROM python:3.11.3

WORKDIR /app
COPY . .

RUN python -m pip install --upgrade pip && \
    pip install -r requirements.txt && \
    python manage.py migrate && \
    python manage.py createsuperuser

EXPOSE 80
CMD python manage.py createsuperuser && python manage.py runserver 0.0.0.0:80
