FROM python:3.11.3

WORKDIR /app
COPY . .

RUN python -m pip install --upgrade pip && \
    pip install -r requirements.txt && \
    python manage.py migrate --run-syncdb && \
    python manage.py createsuperuser --no-input

EXPOSE 80
CMD ["python", "manage.py", "runserver", "0.0.0.0:80"]
