name: Deploy the app to development server
on:
  push:
    branches: ["deploy-dev"]
  
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python env
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3
      
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          python manage.py test
        env:
          SECRET_KEY: release
          QR_CODE: release
          ACCESS_TOKEN_EXPIRE: 3
          REFRESH_TOKEN_EXPIRE: 30

  Deploying:
    runs-on: [self-hosted, dev]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Shut down previous contatiner
        run: docker compose -f docker-compose-dev.yml down
      
      - name: Delete previous docker image
        continue-on-error: true
        run: docker image rm release_backend

      - name: Setup .env file
        run: |
          echo "SECRET_KEY=$SECRET_KEY" >> .env
          echo "ENABLE_PSQL=FALSE" >> .env
          echo "QRCODE=release" >> .env
          echo "ACCESS_TOKEN_EXPIRE=1" >> .env
          echo "REFRESH_TOKEN_EXPIRE=180" >> .env

      - name: Build new docker image
        run: docker build --file dockerfile-dev --tag release_backend .

      - name: Start docker container using new image
        run: docker compose -f docker-compose-dev.yml up -d
        env:
          PSQL_PWD: ${{ secrets.PSQL_PWD_DEV }}